.TH SID 1
.SH NAME
sid \- Serial Image downloader \- download images from site and it's subpages
.SH SYNOPSIS
.B ./sid
[\fB\-d\fR \fIDIRECTORY\fR]
.IR URL
.SH DESCRIPTION
.B sid downloads all the images from a website and it's subpages
.SH OPTIONS
.TP
.BR \-d ", " \-\-dir ", " \-\-directory =\fIDIRECTORY\fR
Chooses directory to save images to. Default is current directory.
.TP
.BR \-h ", " \-\-help
Displays help screen.
.TP
.BR \-v ", " \-\-version
Shows information about version and author.
.SH AUTHOR
Written by Mikołaj Sperkowski.
.SH REPORTING BUGS
Please report bugs to msperkowski@github.com.
.SH COPYRIGHT
This piece of software was written
and is wholly owned by Mikolaj Sperkowski; it cannot be run, published, used, compiled, interpreted, edited, copied or shared in any form without owner's permission.
